name: pikadart
description:
  This Dart package serves as a wrapper for the PokeApi, providing a convenient and efficient way to
  interact with the Pokémon API in Dart projects. The package is designed to simplify the process of
  making API requests and includes an automatic caching mechanism to enhance performance.
version: 1.0.1
repository: https://github.com/seriousdonkey/pikadart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.9
  nock: ^1.2.3
  lints: ^3.0.0
