name: pikadart
description: A Dart package for easy integration with the PokeApi.
version: 1.0.0
repository: https://github.com/seriousdonkey/pikadart

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.1.0
  cached: ^1.6.1
  cached_annotation: ^1.6.0

dev_dependencies:
  build_runner: ^2.4.6
  test: ^1.24.9
  nock: ^1.2.3
  lints: ^3.0.0
